
apiVersion: v1
kind: Pod
metadata:
  name: ytdl-sub
  namespace: jellyfin
spec:
  containers:
  - name: ytdl-sub
    image: ghcr.io/jmbannon/ytdl-sub:latest
    ports:
    - containerPort: 80
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: Asia/Dubai
    - name: DOCKER_MODS
      value: linuxserver/mods:universal-cron
    resources:
      requests:
        memory: "128Mi"
        cpu: "300m"
      limits:
        memory: "500Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /mnt/
      name: download-target
    - name: ytdl-config-vol
      mountPath: config/config.yaml
      subPath: config.yaml
    - name: aela-subscriptions
      mountPath: config/subscriptions.yaml
      subPath: subscriptions.yaml
  volumes:
  - name: download-target
    persistentVolumeClaim:
      claimName: jellyfin-pvc-data
  - name: ytdl-config-vol
    configMap:
      name: config
  - name: aela-subscriptions
    configMap:
      name: aela-subscriptions
