apiVersion: v1
data:
  subscriptions.yaml: |
    # Define any number subscriptions in a single file, or use multiple
    # files to organize (i.e by genre)

    bluey:
      # Mix and match any number of presets to use. You can either lump all settings into
      # a single preset to save some lines, or modularize them and use many.
      preset:
      - "_episode_video_tags"
      - "_episode_nfo_tags"
      - "_jellyfin_tv_show"
      - "_tv_show_by_date"
      - "_episode_base"
      - "_season_by_year"
      - "jellyfin_tv_show_by_date"
      - "season_by_year__episode_by_month_day"
      - "tv_show"
      - "add_subtitles"
      - "sponsorblock"

      overrides:
        # Required to specify for every subscription
        tv_show_name: "Bluey"
        url: ""
        # Optional
        tv_show_genre: "Music"
kind: ConfigMap
metadata:
  name: aela-subscriptions
  namespace: jellyfin
