apiVersion: v1
data:
  sample_config.yaml: |
    #config.yaml
    configuration:
      working_directory: '.ytdl-sub-downloads'

    presets:
      tv_show:
        preset:
        - "jellyfin_tv_show_by_date"
        - "season_by_year__episode_by_month_day" # replace with desired season/episode format
        - "add_subtitles"
        - "sponsorblock"
        - "include_info_json"

        overrides:
          tv_show_directory: "/mnt/Aela" # replace with path to tv show directory

      ####################################################################################################

      # Preset to only download and keep recent videos
      only_recent_videos:

        # Only download videos within the download_range
        date_range:
          after: "today-{download_range}"

        # Stops fetching metadata if the video is out of range (saves time + bandwidth)
        ytdl_options:
          break_on_reject: True

        # Deletes any videos older than download_range. WARNING: do not use
        # "season_by_year__episode_by_download_index" if you plan to delete older videos
        output_options:
          keep_files_after: "today-{download_range}"

        # Set the duration of download_range, defaults to 2 months
        overrides:
          download_range: "2months"

      ####################################################################################################

      # Preset to download subtitles (either by file or embedded)
      add_subtitles:
        subtitles:
          # Embed subtitles into the video
          embed_subtitles: True
          # And/or download them as a file. Uncomment to download as file:
          # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
          # subtitles_type: "srt"

          languages: "en" # supports list of multiple languages
          allow_auto_generated_subtitles: True # allow auto subtitles

      ####################################################################################################

      # Preset to cut sponsor segments from videos
      sponsorblock:
        # If you download using cron, it is wise to add a delay before downloading ad-filled content to
        # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
        # date_range:
        #  before: "today-2days"

        chapters:
          # Remove all of these sponsorblock categories
          sponsorblock_categories:
          - "intro"
          - "outro"
          - "selfpromo"
          - "preview"
          - "interaction"
          - "sponsor"
          - "music_offtopic"
          remove_sponsorblock_categories: "all"
          force_key_frames: False

      ####################################################################################################

      # Preset for the hoarders who want to also save the info.json file
      include_info_json:
        output_options:
          info_json_name: "{episode_file_path}.{info_json_ext}"
kind: ConfigMap
metadata:
  name: ytdl-sub-config
  namespace: jellyfin
